### ISSUE TITLE
Error during build (ng build --prod)

### ISSUE THREAD

**Issue by mattbachmann** [arturovt/ivy-asynchronous-module#9]
[error] E:\ivy-asynchronous-module\node_modules\caniuse-lite\dist\unpacker\feature.js:1

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\ivy-asynchronous-module\node_modules\caniuse-lite\dist\unpacker\index.js:16:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (E:\ivy-asynchronous-module\node_modules\@angular-devkit\build-angular\src\utils\build-browser-features.js:11:24)

**Comment by mattbachmann** [comment]
I have yarn v1.15.2 - what yarn version would you recommend?

**Comment by mattbachmann** [comment]
Upgraded yarn to v1.22.4
Now it worked.
